version: '3.9'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:15rc2-alpine
