name: server
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  conduit: ^4.3.2
  conduit_core: ^4.3.2
  conduit_postgresql: ^4.3.2
  conduit_test: ^4.3.6
  conduit_password_hash: ^4.3.6
  jaguar_jwt: ^3.0.0

dev_dependencies:
  test: ^1.16.5
